spring:
  application:
    name: wallet

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  Liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true
